[SERVICE]
    Flush        5
    Daemon       Off
    Log_Level    info
    Parsers_File parsers.conf

# Apache Access Logs
[INPUT]
    Name              tail
    Path              /var/log/apache2/access.log
    Tag               apache.access
    Parser            apache
    Refresh_Interval  5
    Mem_Buf_Limit     5MB
    Skip_Long_Lines   On

# Apache Error Logs
[INPUT]
    Name              tail
    Path              /var/log/apache2/error.log
    Tag               apache.error
    Refresh_Interval  5
    Mem_Buf_Limit     5MB
    Skip_Long_Lines   On

# Add metadata
[FILTER]
    Name    modify
    Match   *
    Add     hostname ${HOSTNAME}
    Add     job apache

# Forward to Fluentd aggregator
[OUTPUT]
    Name        forward
    Match       *
    Host        fluentd
    Port        24224

    # For TLS encryption to Fluentd, uncomment:
    # tls         on
    # tls.verify  off
    # tls.ca_file /certs/ca.crt

    # Retry configuration
    Retry_Limit 5
